fixing output files.  Now having a problem with consitent output file dimensions

diff --git a/run b/run
--- a/run
+++ b/run
@@ -48,10 +48,10 @@
 
 CmdName=$(basename "$0")
 
-echo "$@" 1>&2
+echo "$0 $@" 1>&2
 
 function sys {
-    [ -n "${opt_n}${opt_v}" ] && echo "$@" 1>&2
+    [ -n "${opt_n}${opt_v}" ] && echo "$(date): $@" 1>&2
     [ -n "$opt_n" ] || "$@"
 }
 
@@ -104,11 +104,11 @@ function niftiIfNeeded {
 	[ -d "$DicomDir" ] || mkdir -p "$DicomDir"
 
 	NiftiFile="${TmpDir}/$(basename "$InputFile" | sed 's/.zip$//; s/.dicom//; s/$/.nii.gz/')"
-	unzip -qq -j -d "$DicomDir" "$InputFile" 
-	SeriesID="$(c3d -dicom-series-list "$DicomDir" | tail -n 1 | awk '{print $NF}')"
+	sys unzip -qq -j -d "$DicomDir" "$InputFile" 
+	SeriesID="$(sys c3d -dicom-series-list "$DicomDir" | tail -n 1 | awk '{print $NF}')"
 
 	# -dicom takes two arguments so  -o follows 
-	c3d -dicom-series-read "$DicomDir" "$SeriesID" -o "$NiftiFile" 
+	sys c3d -dicom-series-read "$DicomDir" "$SeriesID" -o "$NiftiFile" 
 	rm -rf "$DicomDir"
     else
 	echo "$cmd : Unrecognized input type '$InputFile'" 1>&2
@@ -138,7 +138,7 @@ function uploadQaFile {
 	sys fwuploadfile -p "$ProjectPath" -t "$Tags" "$File"
 }
 
-apt install -y wget jq git time 
+sys apt install -y wget jq git time 
 export ASHS_ROOT=/app/ashs
 export PATH="${ASHS_ROOT}/bin":$PATH
 
@@ -167,22 +167,23 @@ then
 EOF
 fi
 
-opt_v=1
+opt_v=-v
 
 while getopts 1:2:c:dnq:tvw: arg
 do
 
     case "$arg" in
 	1|2|c|d|n|q|t|v|w)
-	    eval "opt_${arg}='${OPTARG:=1}'"
+	    eval "opt_${arg}='${OPTARG:=-${arg}}'"
 	    ;;
     esac
 done
 
 shift $(($OPTIND - 1))
 
-git clone 'https://github.com/brainsciencecenter/flywheel.git'
+sys git clone 'https://github.com/brainsciencecenter/flywheel.git'
 export PATH=${FLYWHEEL}/flywheel/bin:$PATH
+export PYTHONPATH=${FLYWHEEL}/flywheel/lib:$PYTHONPATH
 
 sys sed -i 's,| bc,| /usr/bin/bc,' /app/ashs/bin/ashs_grid.sh
 
@@ -195,6 +196,11 @@ jq -r . "$ConfigJsonFile"
 
 T1InputId=$(jq -r '.inputs.T1w.hierarchy.id' "$ConfigJsonFile")
 ProjectId=$(fwget -1 "$T1InputId" | jq -r .parents.project)
+if [ -z "$ProjectId" ]
+then
+	echo "${CmdName} : Could not get parent project id for '${T1InputId}'" 1>&2
+	exit 1
+fi
 
 if [ -z "$opt_q" ]
 then
@@ -204,7 +210,7 @@ then
 	then
 		opt_q="$QaPlacement"
 	else
-		opt_q=$(fwget -1 "$ProjectId" | jq -r '.info.AshsSettings.QaLocation')
+		opt_q=$(sys fwget -1 "$ProjectId" | jq -r '.info.AshsSettings.QaLocation')
 	fi
 fi
 
@@ -221,9 +227,10 @@ then
 	Atlases=( $(jq -r '.config.ASHS_Atlases' "$ConfigJsonFile" | grep -v null | grep -v None) )
 fi
 
+
 if [ -z "$Atlases" ]
 then
-	Atlases=( $(fwget -1 "$ProjectId" | jq -r '.info.AshsSettings.DefaultAtlas' | sed 's/, */ /g') )
+	Atlases=( $(sys fwget -1 "$ProjectId" | jq -r '.info.AshsSettings.DefaultAtlas' | sed 's/, */ /g') )
 fi
 
 #
@@ -246,8 +253,10 @@ then
     echo "${CmdName} : No valid Atlas supplied '$Atlas'" 1>&2
     echo "${CmdName} : Valid Atlases are: "1>&2
     jq -r '.Atlas' "$AshsAtlasConfigFile" 1>&2
-    exit 1
 fi
+
+AnalysisId=$(jq -r '.destination.id' "$ConfigJsonFile" )
+sys fwUpdate --update-fields "label=Ashs Gear Atlases = '${Atlases[*]}' on: $(date)" "$AnalysisId"
 
 for Atlas in "${Atlases[@]}"
 do
@@ -261,7 +270,7 @@ do
 	else
 	    WorkDir=$(sys mktemp -d "/tmp/${Atlas}-wd-XXXXXX" )
 	fi
-	[ -d "$WorkDir" ] || mkdir "$WorkDir"
+	[ -d "$WorkDir" ] || sys mkdir "$WorkDir"
 	TmpDir="$WorkDir"
 
         AtlasJson=$(installAshsAtlas "$Atlas")
@@ -271,6 +280,8 @@ do
 	fi
 	
 	[ -e "$ConfigJsonFile" ] && T1Input=$(jq -r '.inputs.T1w.location.path' "$ConfigJsonFile" | grep -v null)
+	[ -e "$ConfigJsonFile" ] && T1FileId=$(jq -r '.inputs.T1w.object.file_id' "$ConfigJsonFile" | grep -v null)
+
 	[ -n "$opt_1" ] && T1Input="$opt_1"
 
 	[ -n "$opt_t" ] && [ -z "$T1Input" ] && T1Input=$(echo "$AtlasJson" | jq -r .Inputs.T1) 
@@ -281,17 +292,19 @@ do
 	    continue
 	fi
 
+	echo $(fwget -f -1 "$T1FileId"  | jq -r '.parents | .group, .project, .subject, .session, .acquisition'  | (read Group; echo $Group; fwget -1 | jq -r .label)) | sed 's, ,/,g'
+
 	T1NiftiFile=$(niftiIfNeeded "$T1Input")
-	T1NiftiFileStandIn=$(mktemp /tmp/T1-XXXXXXXXXX.nii.gz)
-	cp "$T1NiftiFile" "$T1NiftiFileStandIn"
+
+	sys c3d "$T1NiftiFile" -info
 
 	IdString=$(basename "$T1NiftiFile" | sed -r 's/.gz$//; s/.zip$//; s/(.nii|.nifti|.dicom|.dcm)$//')
 
-	width=$(c3d "$T1NiftiFileStandIn" -info-full | grep "Image Dimensions" | awk '{print $4}' | sed 's/[[,]//g')
-	height=$(c3d "$T1NiftiFileStandIn" -info-full | grep "Image Dimensions" | awk '{print $5}' | sed 's/[[,]//g')
-	sx=$(c3d "$T1NiftiFileStandIn" -info-full | grep "Voxel Spacing" | awk '{print $4}' | sed 's/[][,]//g')
-	sy=$(c3d "$T1NiftiFileStandIn" -info-full | grep "Voxel Spacing" | awk '{print $5}' | sed 's/[][,]//g')
-	sz=$(c3d "$T1NiftiFileStandIn" -info-full | grep "Voxel Spacing" | awk '{print $6}' | sed 's/[][,]//g')
+	width=$(sys c3d "$T1NiftiFile" -info-full | grep "Image Dimensions" | awk '{print $4}' | sed 's/[[,]//g')
+	height=$(sys c3d "$T1NiftiFile" -info-full | grep "Image Dimensions" | awk '{print $5}' | sed 's/[[,]//g')
+	sx=$(sys c3d "$T1NiftiFile" -info-full | grep "Voxel Spacing" | awk '{print $4}' | sed 's/[][,]//g')
+	sy=$(sys c3d "$T1NiftiFile" -info-full | grep "Voxel Spacing" | awk '{print $5}' | sed 's/[][,]//g')
+	sz=$(c3d "$T1NiftiFile" -info-full | grep "Voxel Spacing" | awk '{print $6}' | sed 's/[][,]//g')
 	smax=$(python -c "print(max([$sx,$sy,$sz]))")
 	smin=$(python -c "print(min([$sx,$sy,$sz]))")
 	aspect_ratio_min=$(python -c "print( float($smin)/float($smax))")
@@ -299,7 +312,7 @@ do
 
 	echo "sx = '$sx', sy = '$sy', sz = '$sz', smin = '$smin', smax = '$smax', aspect_ratio_min = '$aspect_ratio_min', aspect_ratio_max = '$aspect_ratio_max'" 
 
-	T1NiftiFileStandInTrimmed=$(echo "${T1NiftiFileStandIn}" | sed 's/.nii.gz/-trimmmed&/')
+	T1NiftiFileTrimmed=$(echo "${T1NiftiFile}" | sed 's/.nii.gz/-trimmmed&/')
 	if (( $width > 40 )) && (( $height > 40 )) ; then
         	if [[ $(echo "$aspect_ratio_max < 3" | bc) == 1 ]] && [[ $(echo "$aspect_ratio_min > 0.33" | bc) == 1 ]] ; then
                 	trim_script=./trim_neck.sh
@@ -307,7 +320,7 @@ do
                 	INTERDIR="$TMPDIR"/inter
                 	if [ ! -d "$MASKDIR" ] ; then mkdir -p "$MASKDIR" ; fi
                 	if [ ! -d "$INTERDIR" ] ; then mkdir -p "$INTERDIR" ; fi
-                	"$trim_script" -m "$MASKDIR" -w "$INTERDIR" "$T1NiftiFileStandIn" "$T1NiftiFileStandInTrimmed" || exit "$?"
+                	"$trim_script" -m "$MASKDIR" -w "$INTERDIR" "$T1NiftiFile" "$T1NiftiFileTrimmed" || exit "$?"
         	else
                 	echo "Wrong scan input: the aspect ratio of the image is < 0.33 or > 3."
                 	exit 1
@@ -316,6 +329,9 @@ do
         	echo "Wrong scan input: the width or/and the height of image is inferior to 40."
         	exit 1
 	fi
+
+	T1SanitizedNiftiFileTrimmed=$(mktemp /tmp/T1-XXXXXXXXXX.nii.gz)
+	cp "$T1NiftiFileTrimmed" "$T1SanitizedNiftiFileTrimmed"
 
 	T2Input="$T1Input"
 	Inputs=$(echo "$AtlasJson" | jq -r '.Inputs | keys | @csv' | sed 's/"//g')
@@ -332,16 +348,17 @@ do
 
 	if [ "$T1NiftiFile" == "$T2NiftiFile" ] 
 	then
-		T2NiftiFileStandIn="$T1NiftiFileStandInTrimmed"
+		T2SanitizedNiftiFile="$T1SanitizedNiftiFileTrimmed"
 	else
-		T2NiftiFileStandIn=$(mktemp /tmp/T2-XXXXXXXXXX.nii.gz)
-		cp "$T2NiftiFile" "$T2NiftiFileStandIn"
+		T2SanitizedNiftiFile=$(mktemp /tmp/T2-XXXXXXXXXX.nii.gz)
+		cp "$T2NiftiFile" "$T2SanitizedNiftiFile"
 	fi
 
+	sys c3d "$T1SanitizedNiftiFileTrimmed" -info
 
 	AtlasDirectory=$(echo "$AtlasJson" | jq -r '.Directory')
 	AshsCmd=(
-	    ashs_main.sh -a "$AtlasDirectory"  -g "$T1NiftiFileStandInTrimmed" -f "$T2NiftiFileStandIn"  -w "$WorkDir"  -P
+	    ashs_main.sh -a "$AtlasDirectory"  -g "$T1SanitizedNiftiFileTrimmed" -f "$T2SanitizedNiftiFile"  -w "$WorkDir"  -P
 	)
 
 	GitBranch="master"
@@ -358,159 +375,7 @@ do
 	SnaplabelsOutputTxtFile="${OutputDir}/${IdString}_${Atlas}_snaplabels.txt"
 	ItkSnapFile=${OutputDir}/${IdString}_${Atlas}_results.itksnap
 
-	sys bash -x ./ashsFwResultsHandler -a "$Atlas" -A "$AtlasDirectory" -c "$ConfigJsonFile" -i "$IdString" -o "$OutputDir" -l "$SHIFT_LEFT" -r "$SHIFT_RIGHT" -I "$SHIFT_ICV" -1 "$T1NiftiFile" -2 "$T2NiftiFile" -t "$T1NiftiFileStandInTrimmed" -w "$WorkDir" -q "$opt_q" || exit "$?"
-#
-#	awk '{ if ( !($1 ~ /^ *[0-9]+$/) || $1 == 0) { print  }  }' "$SnaplabelsInputTxtFile" > "$SnaplabelsOutputTxtFile"
-#	awk '{ if ($1 ~ /^ *[0-9]+$/ && $1 > 0) { gsub(/^"/,"\"Left ",$8); printf("%5d %5d %4d %4d       %2d %2d %2d    %s\n",$1 + '"$SHIFT_LEFT"',$2,$3,$4,$5,$6,$7,$8)   }} ' "$SnaplabelsInputTxtFile" >> "$SnaplabelsOutputTxtFile"
-#	awk '{ if ($1 ~ /^ *[0-9]+$/ && $1 > 0) { gsub(/^"/,"\"Right ",$8); printf("%5d %5d %4d %4d       %2d %2d %2d    %s\n",$1 + '"$SHIFT_RIGHT"',$2,$3,$4,$5,$6,$7,$8)   }} ' "$SnaplabelsInputTxtFile" >> "$SnaplabelsOutputTxtFile"
-#
-#	sys ls "$WorkDir"
-#
-#	#
-#	# Older versions had different tags for T1 under ASHS-HarP than the other atlases
-#	#
-#	#if [ "$Service" == "ASHS-HarP" ]
-#	#then
-#	#    	T1Tag=T1
-#	#else
-#	#        T1Tag=T1-MRI
-#	#fi
-#
-#	T1Tag=T1-MRI
-#	T2Tag=T2-MRI
-#	T1OutputNiftiFile="${OutputDir}/"$(basename "$T1NiftiFileStandInTrimmed")
-#	sys cp "$T1NiftiFile" "$OutputDir"
-#
-#	ITKSnapCmd=( itksnap-wt -layers-add-anat "$T1NiftiFile" -tags-add "$T1Tag" -layers-list -o "$ItkSnapFile" )
-#
-#	if [ -n "$T2InputNeeded" ]
-#	then
-#		T2OutputNiftiFile="${OutputDir}/"$(basename "$T2NiftiFile")
-#		sys cp "$T2NiftiFile" "$T2OutputNiftiFile"
-#
-#		ITKSnapCmd=( itksnap-wt -layers-add-anat "$T1NiftiFileStandInTrimmed" -tags-add "T1Tag" -layers-add-anat "$T2OutputNiftiFile" -tags-add "$T2Tag" -layers-list -o "$ItkSnapFile" )
-#	fi
-#
-#	# Create T1 or T1+T2 MRI result file
-#	sys "${ITKSnapCmd[@]}"
-#
-#	AcquisitionId=$(jq -r '.inputs.T1w.hierarchy.id' "$ConfigJsonFile")
-#	
-#	if [ "$Atlas" == "ASHS-HarP" ]
-#	then
-#
-#		LeftHippocampusVolume=$(sys awk '{print $5}' ${WorkDir}/final/${AshsPrefix}_left_bootstrap_corr_nogray_volumes.txt)
-#		RightHippocampusVolume=$(sys awk '{print $5}' ${WorkDir}/final/${AshsPrefix}_right_bootstrap_corr_nogray_volumes.txt)
-#		sys fwUpdateInfo -f -p .PICSL_sMRI_biomarkers -j "+={\"LeftHippocampusVolume\": ${LeftHippocampusVolume}, \"RightHippocampusVolume\": ${RightHippocampusVolume} }" "$AcquisitionId"
-#
-#		for what in heur corr_usegray corr_nogray
-#		do
-#		    sys c3d														\
-#		    		"$WorkDir/final/${AshsPrefix}_left_lfseg_${what}.nii.gz" -shift $SHIFT_LEFT -replace $SHIFT_LEFT 0	\
-#				"$WorkDir/final/${AshsPrefix}_right_lfseg_${what}.nii.gz" -shift $SHIFT_RIGHT -replace $SHIFT_RIGHT 0	\
-#				-add -type uchar 											\
-#				-o "${OutputDir}/${IdString}_${Atlas}_lfseg_${what}.nii.gz"
-#		done
-#
-#	# Add in the next 3 layers
-#		sys itksnap-wt -i "$ItkSnapFile" \
-#		   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_usegray.nii.gz" -psn "JLF/CL result" \
-#		   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_nogray.nii.gz" -psn "JLF/CL-lite result" \
-#		   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_heur.nii.gz" -psn "JLF result" \
-#		   -labels-clear \
-#		   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_LEFT "Left %s" \
-#		   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_RIGHT "Right %s" \
-#		   -o "$ItkSnapFile"
-#
-#		ItkSnapIcvFile=${OutputDir}/${IdString}_ASHS-ICV_results.itksnap
-#		ItkSnapHarPIcvFile=${OutputDir}/${IdString}_ASHS-HarP-ICV_results.itksnap
-#		if [ -e "$ItkSnapFile" ]
-#		then
-#			sys itksnap-wt -i "$ItkSnapIcvFile" \
-#			   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_usegray.nii.gz" -psn "JLF/CL result" \
-#			   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_nogray.nii.gz" -psn "JLF/CL-lite result" \
-#			   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_heur.nii.gz" -psn "JLF result" \
-#			   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_LEFT "Left %s" \
-#			   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_RIGHT "Right %s" \
-#			   -o "$ItkSnapHarPIcvFile"
-#		fi
-#
-#        fi
-#
-#	if [ "$Atlas" == "ASHS-ICV" ]
-#	then
-#		# Add the ICV image to the project
-#		c3d														\
-#			"$WorkDir/final/${AshsPrefix}_left_lfseg_corr_nogray.nii.gz" -shift $SHIFT_ICV -replace $SHIFT_ICV 0      	\
-#    			-type uchar -o "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz"
-#
-#		ICV=$(c3d "${WorkDir}/final/${AshsPrefix}_left_lfseg_corr_nogray.nii.gz" -dup -lstat | awk '$1 == 1 {print $7}')
-#
-#		sys fwUpdateInfo -f -p .PICSL_sMRI_biomarkers -j "+={\"ICV\": ${ICV} }" "$AcquisitionId"
-#
-#  		sys itksnap-wt -i "$ItkSnapFile" \
-#    		   -las "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz" -psn "ICV" \
-#		   -labels-clear \
-#    		   -labels-add "$SnaplabelsInputTxtFile" "$SHIFT_ICV" "%s" \
-#    		   -o "$ItkSnapFile"
-#
-#		ItkSnapHarPFile=${OutputDir}/${IdString}_ASHS-HarP_results.itksnap
-#	 	ItkSnapHarPIcvFile=${OutputDir}/${IdString}_ASHS-HarP-ICV_results.itksnap
-#		if [ -e "$ItkSnapFile" ]
-#		then
-#  			sys itksnap-wt -i "$ItkSnapHarPFile" \
-#    			   -las "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz" -psn "ICV" \
-#    			   -labels-add "$SnaplabelsInputTxtFile" "$SHIFT_ICV" "%s" \
-#    			   -o "$ItkSnapHarPIcvFile"
-#		fi
-#
-#	fi
-#
-#	sys find "${WorkDir}" -type f
-#
-#
-#	regex=$(echo "$AtlasJson" | jq -r 'if .QaFileRegEx then .QaFileRegEx | @csv else empty end' | sed -r 's/"(.*)"$/(\1)/; s/","/)|(/' )
-#	if [ -z "$regex" ]
-#	then
-#		regex="^$"
-#	fi
-#
-#    	for i in $(find "${WorkDir}" -type f | grep -E "$regex")
-#    	do
-#    	    BaseName=$(basename "$i" )
-#
-#	    echo "opt_q = '$opt_q'" 1>&2
-#	    echo "BaseName = '$BaseName'" 1>&2
-#	    echo "WorkDir = '$WorkDir'" 1>&2
-#	    echo "OutputDir = '$OutputDir'" 1>&2
-#	    echo "IdString = '$IdString'" 1>&2
-#
-#    	    OutputFile="${OutputDir}/${IdString}_${Atlas}_${BaseName}"
-#
-#	    case "$opt_q" in
-#	        Analysis|analysis)
-#    		    sys cp "$i" "${OutputFile}"
-#		    ;;
-#
-#	        "None"|"null")
-#		    true
-#		    ;;
-#
-#		Acquisition|acquisition)
-#		    sys cp "$i" "$OutputFile"
-#
-#		    sys uploadQaFile "$AcquisitionId"  "$OutputFile"
-#		    ;;
-#
-#		*)
-#		    sys cp "$i" "$OutputFile"
-#
-#		    sys uploadQaFile "$opt_q"  "$OutputFile"
-#		    ;;
-#
-#            esac
-#	done
-#	
-#	sys ls -l "$OutputDir"
+	sys bash -x ./ashsFwResultsHandler $opt_v -a "$Atlas" -A "$AtlasDirectory" -c "$ConfigJsonFile" -i "$IdString" -o "$OutputDir" -l "$SHIFT_LEFT" -r "$SHIFT_RIGHT" -I "$SHIFT_ICV" -1 "$T1NiftiFile" -2 "$T2NiftiFile" -t "$T1NiftiFileTrimmed" -w "$WorkDir" -q "$opt_q" || exit "$?"
+
 done
 
