updating atlas test input

diff --git a/run b/run
--- a/run
+++ b/run
@@ -123,7 +123,9 @@ export PATH="${ASHS_ROOT}/bin":$PATH
 AshsAtlasesDir="/app/atlas/data"
 AshsAtlasConfigFile="/app/AshsAtlasesConfig.json"
 ConfigJsonFile="config.json"
+InputDir=${FLYWHEEL_INPUT}
 OutputDir=${FLYWHEEL_OUTPUT}
+TestDataDir=${FLYWHEEL}/testdata
 
 SHIFT_LEFT=0
 SHIFT_RIGHT=100
@@ -140,11 +142,11 @@ then
 EOF
 fi
 
-while getopts 1:2:c:dnvw: arg
+while getopts 1:2:c:dntvw: arg
 do
 
     case "$arg" in
-	1|2|c|d|n|v|w)
+	1|2|c|d|n|t|v|w)
 	    eval "opt_${arg}=${OPTARG:=1}"
 	    ;;
     esac
@@ -171,23 +173,13 @@ TmpDir="$WorkDir"
 
 if [ -e "$ConfigJsonFile" ]
 then
-	T1Input=$(jq -r '.inputs.T1w.location.path' "$ConfigJsonFile")
-	Atlases=( $(jq -r '.config.ASHS_Atlases' "$ConfigJsonFile") )
+	T1Input=$(jq -r '.inputs.T1w.location.path' "$ConfigJsonFile" | grep -v null)
+	Atlases=( $(jq -r '.config.ASHS_Atlases' "$ConfigJsonFile" | grep -v null) )
 fi
 
-[ -n "$opt_1" ] && T1Input="$opt_1"
-
-if [ -z "T1Input" ]
-then
-    echo "$CmdName : reqiured argument T1 missing. No -1 argument and not found in config.json" 1>&2
-    echo "$syntax" 1>&2
-fi
-
-
-T1NiftiFile=$(niftiIfNeeded "$T1Input")
-IdString=$(basename "$T1NiftiFile" | sed -r 's/.gz$//; s/.zip$//; s/(.nii|.nifti|.dicom|.dcm)$//')
-
-
+#
+# *** The atlas checks should be done inthe for loop
+#
 if [ -n "$1" ] && [ "$1" == "all" ]
 then
     Atlases=( $(jq -r '.Atlas' "$AshsAtlasConfigFile" | sort ) )
@@ -209,23 +201,40 @@ then
     jq -r '.Atlas' "$AshsAtlasConfigFile" 1>&2
     exit 1
 fi
-	
+
 for Atlas in "${Atlases[@]}"
 do
+	unset T1Input
+	unset T2Input
+
         AtlasJson=$(installAshsAtlas "$Atlas")
         if [ -z "$AtlasJson" ]
 	then
 	    exit 1
 	fi
 	
+	[ -n "$opt_1" ] && T1Input="$opt_1"
+
+	[ -n "$opt_t" ] && [ -z "$T1Input" ] && T1Input=$(echo "$AtlasJson" | jq -r .Inputs.T1)
+	if [ -z "$T1Input" ]
+	then
+	    echo "$CmdName : reqiured argument T1 missing. No -1 argument and not found in config.json" 1>&2
+	    echo "$syntax" 1>&2
+	    continue
+	fi
+
+	T1NiftiFile=$(niftiIfNeeded "$T1Input")
+	IdString=$(basename "$T1NiftiFile" | sed -r 's/.gz$//; s/.zip$//; s/(.nii|.nifti|.dicom|.dcm)$//')
 
 	T2Input="$T1Input"
-	Inputs=$(echo "$AtlasJson" | jq -r '.Inputs | @csv' | sed 's/"//g')
+	Inputs=$(echo "$AtlasJson" | jq -r '.Inputs | keys | @csv' | sed 's/"//g')
 	if echo "$Inputs" | grep -q T2
 	then
 	    T2InputNeeded=1
-	    T2Input=$(jq -r '.inputs.T2w.location.path' "$ConfigJsonFile")
+	    T2Input=$(jq -r '.inputs.T2w.location.path' "$ConfigJsonFile" | grep -v null)
 	    [ -n "$opt_2" ] && T2Input="$opt_2"
+	    [ -n "$opt_t" ] && [ -z "$T2Input" ] && T2Input=${TestDataDir}/$(echo "$AtlasJson" | jq -r .Inputs.T2)
+
 	fi
 
 	T2NiftiFile=$(niftiIfNeeded "$T2Input")
@@ -249,7 +258,7 @@ do
 
 	AshsPrefix=$(basename "$WorkDir")
 	SnaplabelsInputTxtFile="${AtlasDirectory}/snap/snaplabels.txt"
-	SnaplabelsOutputTxtFile="${OutputDir}/${IdString}-snaplabels.txt"
+	SnaplabelsOutputTxtFile="${OutputDir}/${IdString}_${Atlas}_snaplabels.txt"
 	ItkSnapFile=${OutputDir}/${IdString}_${Atlas}_results.itksnap
 
 	awk '{ if ( !($1 ~ /^ *[0-9]+$/) || $1 == 0) { print  }  }' "$SnaplabelsInputTxtFile" > "$SnaplabelsOutputTxtFile"
